apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc-deployment
spec:
  replicas: 2
  minReadySeconds: 3
  selector:
    matchLabels:
      app: spring-pet-clinic
  template:
    metadata:
      labels:
        app: spring-pet-clinic
    spec:
      containers:
        - name: pet-clinic
          image: 430118814498.dkr.ecr.ap-south-1.amazonaws.com/spring-pet-clinic:1.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 400Mi
            requests:
              cpu: 250m
              memory: 300Mi
